# -*-oding:utf-8-*-
from xml.dom import minidom, Node
import cv2
path='./data.txt'
res="./VOCdevkit/VOC2007/JPEGImages/"
savePath='./VOCdevkit/VOC2007/Annotations/'
count=0
with open("./data.txt",'r') as f:
    lines=f.readlines()
for line in lines[:]:
    info=line.split(' ')
    im=cv2.imread(res+info[0])
    w=im.shape[1]
    h=im.shape[0]
    d=im.shape[2]
    doc=minidom.Document()
    annotation=doc.createElement('annotation')
    doc.appendChild(annotation)
    folder=doc.createElement('folder')
    folder.appendChild(doc.createTextNode('VOC2007'))
    filename=doc.createElement('filename')
    print("info[0]:",info[0])
    filename.appendChild(doc.createTextNode(info[0]))
    source=doc.createElement('source')
    database=doc.createElement('database')
    database.appendChild(doc.createTextNode('The VOC2007 Database'))
    # annotation=doc.createElement('annotation')
    # annotation.appendChild(doc.createTextNode('PASCAL VOC2007'))
    # image=doc.createElement('image')
    # image.appendChild(doc.createTextNode('flickr'))
    # flickrid=doc.createElement('flickrid')
    # flickrid.appendChild(doc.createTextNode('341012865'))
    source.appendChild(database)
    # source.appendChild(annotation)
    # source.appendChild(image)
    # source.appendChild(flickrid)
    owner=doc.createElement('owner')
    # flickrid=doc.createElement('flickrid')
    # flickrid.appendChild(doc.createTextNode('Fried Camels'))
    name=doc.createElement('name')
    name.appendChild(doc.createTextNode('AM'))
    # owner.appendChild(flickrid)
    owner.appendChild(name)
    annotation.appendChild(folder)
    annotation.appendChild(filename)
    annotation.appendChild(source)
    annotation.appendChild(owner)
    segmented=doc.createElement('segmented')
    segmented.appendChild(doc.createTextNode('0'))
    annotation.appendChild(segmented)
    size=doc.createElement('size')
    width=doc.createElement('width')
    width.appendChild(doc.createTextNode(str(w)))
    size.appendChild(width)
    height=doc.createElement('height')
    height.appendChild(doc.createTextNode(str(h)))
    size.appendChild(height)
    annotation.appendChild(size)
    length=len(info)
    obj_num=(length-1)/5
    print(length,obj_num)
    for i in range(int(obj_num)):
        object=doc.createElement('object')
        pose=doc.createElement('pose')
        pose.appendChild(doc.createTextNode('frontal'))
        truncated=doc.createElement('truncated')
        truncated.appendChild(doc.createTextNode('0'))
        difficult=doc.createElement('difficult')
        difficult.appendChild(doc.createTextNode('0'))
        object.appendChild(pose)
        object.appendChild(truncated)
        object.appendChild(difficult)
        name=doc.createElement('name')
        name.appendChild(doc.createTextNode('wood'))
        object.appendChild(name)
        bndbox=doc.createElement('bndbox')
        xmin=doc.createElement('xmin')
        ymin=doc.createElement('ymin')
        xmax=doc.createElement('xmax')
        ymax=doc.createElement('ymax')
        xmin.appendChild(doc.createTextNode(info[i*5+1]))
        ymin.appendChild(doc.createTextNode(info[i * 5 + 2]))
        xmax.appendChild(doc.createTextNode(info[i * 5 + 3]))
        ymax.appendChild(doc.createTextNode(info[i * 5 + 4]))
        bndbox.appendChild(xmin)
        bndbox.appendChild(ymin)
        bndbox.appendChild(xmax)
        bndbox.appendChild(ymax)
        object.appendChild(bndbox)
        annotation.appendChild(object)
    filename=info[0].split('.')
    savefile=open(savePath+filename[0]+'.xml','wb')
    savefile.write(doc.toprettyxml(encoding='utf-8'))
    savefile.close()
    count+=1
    print(count)
